(def in '(A ((B) (C)) (D) (K) L))

(def a (first in))
(def b (first (first (first (rest in)))))
(def c_wrapped (first (rest (first (rest in)))))
(def c (first c_wrapped))
(def d_wrapped (first (rest (rest in))))
(def d (first d_wrapped))
(def abc (cons a (cons b (cons c nil))))
(def adWcW (cons a (cons d_wrapped (cons c_wrapped nil))))
(def dab (cons d (cons a (cons b nil))))
(println a)
(println d)
(println d_wrapped)
(println abc)
(println adWcW)
(println dab)